---
name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - uses: pnpm/setup@v2
        with:
          cache: true

      - name: Run format check
        run: pnpm run format:check

      - name: Run lint check
        run: pnpm run lint

      # - name: Run stylelint check
      #   run: pnpm run stylelint

      - name: Build project
        run: pnpm run build
